sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else git
      rev-parse --short HEAD; fi)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_REPO/single-user single-user
    - docker tag $DOCKER_REPO/single-user $DOCKER_REPO/single-user:$TAG
    - docker build -t $DOCKER_REPO/single-user-aginfra single-user-aginfra
    - docker tag $DOCKER_REPO/single-user-aginfra $DOCKER_REPO/single-user-aginfra:$TAG
    - docker build -t $DOCKER_REPO/hub hub
    - docker tag $DOCKER_REPO/hub $DOCKER_REPO/hub:$TAG
    after_success:
    - docker push $DOCKER_REPO/single-user
    - docker push $DOCKER_REPO/single-user:$TAG
    - docker push $DOCKER_REPO/single-user-aginfra
    - docker push $DOCKER_REPO/single-user-aginfra:$TAG
    - docker push $DOCKER_REPO/hub
    - docker push $DOCKER_REPO/hub:$TAG
env:
  global:
  - DOCKER_REPO=eginotebooks
  - secure: n4KBQ/+Gr/I+xoTve7CuPFnZeVjjk9gf/2B9NWY1IN8FLsfeJy/vi/Am2czf93Zynu6QWunHrf1CMXZ/PN9ra/fiSKgXbjpC+nfKI+1SK/prPNN5psNR0H8/vHV2ppLYPJOQorD0DL7w3blGPS0cSWjSAOUfUyTUhY54RAkNs615XsXIA6eTRq4d7Z7hcbWNfLaW9h79S64l9nknydsziGxAI5z9aN2TUUC1YoH8UXzNFE//f/sywtBhse9ovg644yVnCo3aecwZ/YCSkVDACDWmsxicR+YGeteyrM7kpcY2yw8M4x/bhYD9/pd0W4PxTq+A8a88oj14VnRadEwNhphh7VydE0m4MIJrwJrJTH2++4qb+q5UZPz0L9JhvjETVTqQRZw/Mfd7cHr1xE4VcfvK85KghdWXJn9QB2jtZ5RIVsxRw47xBZMJkmZH8wXl+HR7bDPLz6nx2WrEy9NEmyv8HBYIYap8pFTXw62ZK/k0K2Mj6wP8uUvsopNjnRX7+XrvmcECCwZVCyvMDFKtwvhCp2QySS/EIDwjzInZvwJK3RAJdBXtGsjltLN0ZHk9zlh7trN86Io4586jU+0K0jvTpou2eaCAaD5M07IIdoX1BxRwFL8RfCS9SvgeP+YXMrn9o/vACp8bNj4VkWAaSj1Po/KvLaWGsom5DCbo8kI=
  - secure: j33vDA3yDdQl/UMcElqqQ6bSaMRbDr48wpcSsigf9S16ixWGBLmpG4hVq6lyMNJH6iHfX2xm0YsImV9I5SPNQ7iK91uWxo8Wvv0vdmKeA3yzmt72+8+Hu3WSpMO/4F3nf8WeN5KLnkipeULjMjiKLES6Ns7m0tCC8JsuSuPWQ8lZTg6PDfd4JvP8ubKnnMyBSy1HkIlSzo1NSbLyXzfscaRZK3kMxSSYR/sPn26HyKi8+zijhY9FPstrZ+5Tgk0iKBzf83Yb/UeFGlheUQ/ARKCYHKqXLcfbVJmUgdbPtY0Xs5NdltbNr7ROGBbJB/Xd4aU5yVP9w2IdB4SuveloYZhg4hIDmeGO7xUBRpACqKzMPF29BPkbol72C0NsmpZvxJUjSc3PuBKvyrtfU0v5cD+wfIZdF6exB456hka9A4krTj8+sAc16ksPadrO4hMZJfYSrQV8pla3z6V17cuhbn/QKdtMuGzzaFY5VxEwHxOoEbHdQD5hAm/lDbesY8ibfTkXnV3OG2pFqgivyObYrvA49tVj8xTtsDwX8haJj063KPkTL9q9prqRCTVgWXcsBvVflygazc9yajVsdOuk9ONk8i5wPYEywuvizpJCGU0SfgSg2I4PakXualOPk6PgTlBlan6Yke1OyT+zxZHMQ4xqNAcnBsGDjyfAxoK5ePs=
