sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else git rev-parse --short HEAD; fi)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t singleuser single-user 
    - docker tag singleuser $DOCKER_REPO/single-user:$TAG
    - docker build -t hub hub 
    - docker tag hub $DOCKER_REPO/hub:$TAG
    after_success:
    - docker push $DOCKER_REPO/single-user
    - docker push $DOCKER_REPO/hub
